-- MySQL Script generated by MySQL Workbench
-- Sun Jan 15 19:51:31 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema done
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema done
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `done` DEFAULT CHARACTER SET latin1 ;
USE `done` ;

-- -----------------------------------------------------
-- Table `done`.`tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `done`.`tags` (
  `tagid` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `user` INT(11) NULL DEFAULT NULL,
  `createdAt` DATETIME NULL DEFAULT NULL,
  `updatedAt` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`tagid`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `done`.`tasks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `done`.`tasks` (
  `taskid` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `deadline` DATE NULL DEFAULT NULL,
  `finished` DATE NULL DEFAULT NULL,
  `status` INT(11) NULL DEFAULT NULL,
  `priority` INT(11) NULL DEFAULT NULL,
  `description` VARCHAR(200) NULL DEFAULT NULL,
  `tag` INT(11) NULL DEFAULT NULL,
  `user` INT(11) NULL DEFAULT NULL,
  `createdAt` DATETIME NULL DEFAULT NULL,
  `updatedAt` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`taskid`))
ENGINE = InnoDB
AUTO_INCREMENT = 24
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `done`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `done`.`user` (
  `userid` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NULL DEFAULT NULL,
  `lastname` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `todos` INT(11) NULL DEFAULT NULL,
  `dones` INT(11) NULL DEFAULT NULL,
  `productivitypts` INT(11) NULL DEFAULT NULL,
  `admin` INT(11) NULL DEFAULT NULL,
  `tasksperday` INT(11) NULL DEFAULT NULL,
  `createdAt` DATETIME NULL DEFAULT NULL,
  `updatedAt` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`userid`),
  UNIQUE INDEX `email` (`email` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
USE `done`;

DELIMITER $$
USE `done`$$
CREATE
DEFINER=`gretinabaza`@`%`
TRIGGER `done`.`tasks_AFTER_INSERT`
AFTER INSERT ON `done`.`tasks`
FOR EACH ROW
BEGIN
	UPDATE user SET todos = todos + 1 WHERE userid = NEW.user;
END$$

USE `done`$$
CREATE
DEFINER=`gretinabaza`@`%`
TRIGGER `done`.`tasks_AFTER_UPDATE`
AFTER UPDATE ON `done`.`tasks`
FOR EACH ROW
BEGIN
	IF NEW.status <> OLD.status AND NEW.status = 1 THEN
		UPDATE user SET todos = todos - 1 WHERE userid = OLD.user;
        UPDATE user SET dones = dones + 1 WHERE userid = OLD.user;
		
        UPDATE user SET productivitypts = productivitypts + NEW.priority WHERE userid = OLD.user;
        
	ELSEIF NEW.status <> OLD.status AND NEW.status = 0 THEN
		UPDATE user SET todos = todos + 1 WHERE userid = OLD.user;
        UPDATE user SET dones = dones - 1 WHERE userid = OLD.user;
		
        UPDATE user SET productivitypts = productivitypts - NEW.priority WHERE userid = OLD.user;
    END IF;
END$$


DELIMITER ;
